# Generated by Django 4.2.30 on 2026-08-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_businessimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='business_message',
            field=models.TextField(blank=True, help_text='Message from business to customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Customer notes'),
        ),
    ]
