# Generated by Django 4.2.30 on 2026-08-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_booking_business_message_alter_booking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_reply',
            field=models.TextField(blank=True, help_text='Reply from customer to business'),
        ),
    ]
