# Generated by Django 4.2.30 on 2026-08-25 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_booking_customer_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='working_days',
            field=models.IntegerField(default=5, help_text='Number of working days in a week'),
        ),
        migrations.AlterField(
            model_name='business',
            name='closing_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='business',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
