# Generated by Django 4.2.30 on 2026-08-26 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_staff_stafftimeoff_staffbreak_staffavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary_type',
            field=models.CharField(choices=[('monthly', 'Monthly Fixed'), ('hourly', 'Hourly Rate'), ('commission', 'Commission Only')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='stafftimeoff',
            name='leave_type',
            field=models.CharField(choices=[('paid', 'Paid Leave'), ('unpaid', 'Unpaid Leave'), ('sick', 'Sick Leave')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='stafftimeoff',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month this payroll applies to')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('incentives', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='dashboard.staff')),
            ],
        ),
    ]
