# Generated by Django 4.2.30 on 2026-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_businesstimeoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='primary_color',
            field=models.CharField(default='#4F46E5', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='secondary_color',
            field=models.CharField(default='#F1F5F9', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
