# Generated by Django 5.2.17 on 2026-09-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_booking_services_alter_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer phone number for WhatsApp', max_length=20),
        ),
    ]
