# Generated by Django 5.2.17 on 2026-09-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_booking_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='auto_accept_bookings',
            field=models.BooleanField(default=False, help_text='Automatically confirm new bookings'),
        ),
    ]
